version: '3'
services:
  apache:
    build: ./apache
    container_name: apache
    restart: always
    ports:
      - 7777:80 # Puerto público para Apache
    volumes:
      - ./web/static:/usr/local/apache2/htdocs/static # Sirve la carpeta 'static' desde el contenedor de Python
      - ./apache/config/demo.apache.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - python
    networks:
      - internal

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "999:999"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./Salas.sql:/docker-entrypoint-initdb.d/Salas.sql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
    networks:
      - internal

  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      PYTHONBUFFERED: 1
    depends_on:
      - mariadb
    networks:
      - internal

networks:
  internal:
    driver: bridge
