version: '3'
services:
  apache:
    build: ./apache/
    container_name: apacheb8
    restart: always
    volumes:
      - ./apache/static:/var/www/html
    ports:
      - 6108:80
    depends_on:
      - python

  python:
    build: .
    container_name: pythonb8
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    expose:
      - 8080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadbb8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./Salas.sql:/docker-entrypoint-initdb.d/setup.sql
    user: mysql
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb8
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7108:80
    depends_on:
      - mariadb