# Cargar módulos necesarios para proxy
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# Configuración del VirtualHost
<VirtualHost *:80>
    ServerName localhost

    # Redirige todo el tráfico /api/ a Python
    ProxyPass /api/ http://python:8080/
    ProxyPassReverse /api/ http://python:8080/

    # Servir contenido estático desde htdocs (monto la carpeta static)
    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
