# Cargar módulos necesarios para proxy y MPM
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
# Eliminar mod_alias si no es necesario o está causando problemas

# Configuración del VirtualHost
<VirtualHost *:80>
    ServerName localhost

    # Redirige todo el tráfico /api/ a Python
    ProxyPass /api/ http://python:8080/
    ProxyPassReverse /api/ http://python:8080/

    # Servir contenido estático desde htdocs (monto la carpeta static)
    DocumentRoot "/usr/local/apache2/htdocs"
    
    # Redirigir /static/ a la carpeta correcta dentro de Apache
    Alias /static/ /usr/local/apache2/htdocs/static/
    
    # Asegurarse de que Apache pueda servir el contenido de la carpeta /static/
    <Directory "/usr/local/apache2/htdocs/static">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
